// Regenerates web/src/abi/*.ts from the Solidity sources with `forge inspect`.
// Run from web/: `npm run abi` (needs foundry on PATH).
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const web = join(dirname(fileURLToPath(import.meta.url)), '..');
const root = join(web, '..');

const contracts = [
  ['Vault', 'vaultAbi'],
  ['VaultFactory', 'factoryAbi'],
  ['IFWA', 'fwaAbi'],
];

for (const [name, exportName] of contracts) {
  const json = execFileSync('forge', ['inspect', name, 'abi', '--json'], { cwd: root, encoding: 'utf8' });
  const abi = JSON.parse(json);
  const body = `// Generated by \`npm run abi\` from ${name}. Do not edit.\nexport const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(web, 'src', 'abi', `${name}.ts`), body);
  console.log(`wrote src/abi/${name}.ts (${abi.length} entries)`);
}
